version: '3.8'
services:
  backend:
    image: eks-backend-${GIT_BRANCH}:1.0
    environment:
    # get this variable from .env file
      - TEST_VARIABLE=${TEST_VARIABLE}
    build: ./backend
    restart: on-failure
    ports:
        #target port : container app run port 
      - 8000:8000
    volumes:
      - ./backend:/app
  frontend:
    image: eks-frontend-${GIT_BRANCH}:1.0
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules