version: '3.8'
services:
  backend:
    image: ${ECR_REGISTRY}:eks-backend-${GIT_BRANCH}-latest
    container_name: backend-container
    environment:
    # get this variable from .env file
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    restart: on-failure
    ports:
        #target port : container app run port 
      - 8000:8000
    networks:
      - app-network

  frontend:
    image: ${ECR_REGISTRY}:eks-frontend-${GIT_BRANCH}-latest
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"  # Expose port 80 for Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx configuration file
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

